### ISSUE TITLE
Fix remaining pep8 issues

### ISSUE THREAD

**Issue by biswaz** [raksha-life/rescuekerala#1124]
I have formatted all the files using black. From now all pep8 directives except `E501` must be respected.

Adding the remaining ones below:

- [ ] ./mainapp/views.py:189:5: E722 do not use bare 'except'
- [ ] ./mainapp/views.py:478:5: E722 do not use bare 'except'
- [ ] ./mainapp/views.py:515:5: E722 do not use bare 'except'
- [ ] ./mainapp/views.py:542:5: E722 do not use bare 'except'
- [ ] ./mainapp/views.py:691:5: F841 local variable 'body_rows' is assigned to but never used
- [ ] ./mainapp/views.py:705:12: E711 comparison to None should be 'if cond is None:'
- [ ] ./mainapp/csvimporter.py:16:5: E722 do not use bare 'except'
- [ ] ./mainapp/csvimporter.py:61:37: E711 comparison to None should be 'if cond is None:'
- [ ] ./mainapp/csvimporter.py:82:37: E711 comparison to None should be 'if cond is not None:'
- [ ] ./mainapp/csvimporter.py:86:42: E711 comparison to None should be 'if cond is not None:'
- [ ] ./mainapp/models/models.py:112:19: W605 invalid escape sequence '\+'
- [ ] ./mainapp/models/models.py:112:30: W605 invalid escape sequence '\-'
- [ ] ./mainapp/models/models.py:112:49: W605 invalid escape sequence '\d'
- [ ] ./mainapp/models/models.py:243:19: W605 invalid escape sequence '\+'
- [ ] ./mainapp/models/models.py:243:30: W605 invalid escape sequence '\-'
- [ ] ./mainapp/models/models.py:243:49: W605 invalid escape sequence '\d'
- [ ] ./mainapp/models/models.py:321:19: W605 invalid escape sequence '\+'
- [ ] ./mainapp/models/models.py:321:30: W605 invalid escape sequence '\-'
- [ ] ./mainapp/models/models.py:321:49: W605 invalid escape sequence '\d'
- [ ] ./mainapp/models/models.py:643:53: E231 missing whitespace after ','
- [ ] ./mainapp/models/models.py:695:19: W605 invalid escape sequence '\+'
- [ ] ./mainapp/models/models.py:695:30: W605 invalid escape sequence '\-'
- [ ] ./mainapp/models/models.py:695:49: W605 invalid escape sequence '\d'
- [ ] ./mainapp/models/models.py:832:19: W605 invalid escape sequence '\+'
- [ ] ./mainapp/models/models.py:832:30: W605 invalid escape sequence '\-'
- [ ] ./mainapp/models/models.py:832:49: W605 invalid escape sequence '\d'
- [ ] ./mainapp/models/models.py:890:26: E711 comparison to None should be 'if cond is not None:'
- [ ] ./mainapp/tests/test_views.py:419:9: F841 local variable 'rescue_camp_tcr_1_model' is assigned to but never used
- [ ] ./mainapp/tests/test_views.py:426:9: F841 local variable 'rescue_camp_tcr_2_model' is assigned to but never used
- [ ] ./mainapp/tests/test_views.py:433:9: F841 local variable 'rescue_camp_tcr_3_model' is assigned to but never used
- [ ] ./mainapp/utils/sms.py:38:17: E711 comparison to None should be 'if cond is not None:'
- [ ] ./mainapp/utils/sms.py:40:13: E711 comparison to None should be 'if cond is not None:'
- [ ] ./mainapp/utils/sms.py:42:14: E711 comparison to None should be 'if cond is not None:'
- [ ] ./mainapp/utils/sms.py:44:17: E711 comparison to None should be 'if cond is None:'
- [ ] ./floodrelief/test_settings.py:1:1: F403 'from .settings import *' used; unable to detect undefined names
- [ ] ./floodrelief/test_settings.py:1:1: F401 '.settings.*' imported but unused
- [ ] ./floodrelief/urls.py:36:68: E231 missing whitespace after ','
- [ ] ./floodrelief/settings.py:15:1: F401 'dj_database_url' imported but unused
- [ ]

**Comment by bobinson** [comment]
looks good
